// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}
